### ISSUE TITLE
How to build this application?

### ISSUE THREAD

**Issue by surjithbs17** [xiefei0117/REVISE-national-charging-infrastructure-model#1]
@xiefei0117 
Can you update the instructions to build this application?

**Comment by xiefei0117** [comment]
@surjithbs17 , thank you for your suggestion, I will add those instructions soon. Just FYI, the whole project is built using Eclipse Java project structure. If you download the whole folder, you should be able to load the project in Eclipse and recompile it. Please let me know if it does not work. Thanks.

**Comment by xiefei0117** [comment]
> @xiefei0117
> Can you update the instructions to build this application?

I have separated the files into two folders. One contains the built one, and by following the readme.pdf file, you can run it in your machine. The other one contains the source code.
